Adding APIM support

diff --git a/.azure-pipelines/productscs-kubernetes-releasepipeline.yaml b/.azure-pipelines/productscs-kubernetes-releasepipeline.yaml
--- a/.azure-pipelines/productscs-kubernetes-releasepipeline.yaml
+++ b/.azure-pipelines/productscs-kubernetes-releasepipeline.yaml
@@ -1,5 +1,3 @@
-# Azure DevOps Release Pipeline YAML for Kubernetes Deployment with dynamic BuildId tag
-
 trigger: none
 
 variables:
@@ -18,13 +16,20 @@ variables:
   value: 'bookstoreaure.azurecr.io'
 - name: imageTag
   value: 84
+- name: apimResourceGroup
+  value: 'BookStoreRG'  # Replace if different
+- name: apimInstance
+  value: 'bookstore-apim'  # Your APIM instance name
 
 stages:
+# -----------------------------
+# Stage 1: Deploy to AKS
+# -----------------------------
 - stage: Deploy
-  displayName: 'Deploy to AKS'
+  displayName: 'Deploy ProductService to AKS'
   jobs:
   - job: DeployToKubernetes
-    displayName: 'Create Kubernetes Secret & Deploy ProductService'
+    displayName: 'Deploy ProductService to Kubernetes'
     pool:
       vmImage: 'ubuntu-latest'
     steps:
@@ -95,3 +100,59 @@ stages:
                 targetPort: 80
             type: LoadBalancer
           EOF
+
+# -----------------------------
+# Stage 2: Import to APIM
+# -----------------------------
+- stage: ImportToAPIM
+  displayName: 'Import ProductService API to APIM'
+  dependsOn: Deploy
+  condition: succeeded()
+  jobs:
+  - job: ImportAPI
+    displayName: 'Import Swagger to APIM'
+    pool:
+      vmImage: 'ubuntu-latest'
+    steps:
+    - task: AzureCLI@2
+      displayName: 'Import API into APIM with retries'
+      inputs:
+        azureSubscription: '$(azureSubscription)'
+        scriptType: 'bash'
+        scriptLocation: 'inlineScript'
+        inlineScript: |
+          echo "Getting AKS credentials..."
+          az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksClusterName) --overwrite-existing
+
+          echo "Trying to retrieve External IP for ProductService..."
+          EXTERNAL_IP=""
+          RETRIES=10
+
+          while [ -z "$EXTERNAL_IP" ] && [ $RETRIES -gt 0 ]; do
+            echo "Waiting for External IP... ($RETRIES attempts left)"
+            EXTERNAL_IP=$(kubectl get svc productservice -n $(namespace) -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
+            if [ -z "$EXTERNAL_IP" ]; then
+              sleep 15
+              RETRIES=$((RETRIES - 1))
+            fi
+          done
+
+          if [ -z "$EXTERNAL_IP" ]; then
+            echo "Failed to get External IP after multiple retries."
+            exit 1
+          fi
+
+          echo "External IP obtained: $EXTERNAL_IP"
+          echo "Swagger URL: http://$EXTERNAL_IP/swagger/v1/swagger.json"
+
+          echo "Importing ProductService API into APIM..."
+          az apim api import \
+            --resource-group $(apimResourceGroup) \
+            --service-name $(apimInstance) \
+            --api-id productservice-api \
+            --path product \
+            --display-name "ProductService API" \
+            --specification-url "http://$EXTERNAL_IP/swagger/v1/swagger.json" \
+            --specification-format OpenApi
+
+          echo "API imported successfully to APIM!"
